version: "3"

services:
  auth:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - MYSQL_URL=jdbc:mysql://mysql/auth?useSSL=false&characterEncoding=UTF-8
    restart: unless-stopped

  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=auth
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
